name: fiction

on: workflow_dispatch

jobs:
  build:
    name: Generate FHIR profiles
    runs-on: ubuntu-latest

    steps:
      - run: lscpu
        name: Available CPU

      - run: free -h
        name: Available memory
