name: fiction

on: workflow_dispatch

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0 
          submodules: 'recursive'

      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.5.0
        with:
          babashka-version: 0.8.156

      - name: Set tag env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/setup-node@v3.4.1
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"

      - uses: actions/setup-java@v3.5.0
        with:
          distribution: "temurin"
          java-version: "18"

      - uses: DeLaGuardo/setup-clojure@9.5
        with:
          cli: 1.11.1.1155

      - run: lscpu
        name: Available CPU

      - run: free -h
        name: Available memory
        
      - run: sudo cat /home/runner/.m2/settings.xml
        name: Java settings
