name: publish-npm-package

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/setup-node@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: 1.10.1.693
      - run: make init
      - run: make zen-profiles node_modules="node_modules/" zrc="zrc/node_modules/" ver="${{ env.RELEASE_VERSION }}"
      - run: npm publish --all
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
