name: publish-npm-package

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Generate FHIR profiles
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.8.156

      - name: Set tag env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'

      - uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: 1.10.1.693

      - run: bb init
        name: Install npm FHIR packages

      - run: bb init-r3
        name: Install npm R3 packages

      - run: bb zen-profiles node_modules="node_modules/" zrc="zrc/node_modules/" ver="${{ env.RELEASE_VERSION }}"
        name: Generate npm Zen packages

      - name: Genrate npm R3 Zen packages
        run: bb zen-profiles node_modules="r3/node_modules/" zrc="zrc/node_modules/" ver="${{ env.RELEASE_VERSION }}"

      - run:
          for folder in $(ls -d zrc/node_modules/*); do npm publish $folder --access=public; done
        name: Publish npm Zen packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
