name: publish-npm-package

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set tag Env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/setup-node@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: 1.10.1.693
      - run: make init
        name: Install npm FHIR packages
      - run: make zen-profiles node_modules="node_modules/" zrc="zrc/node_modules/" ver="${{ env.RELEASE_VERSION }}"
        name: Generate npm Zen packages
      - run: npm login
      - run:
          for folder in $(ls -d zrc/node_modules/*); do npm publish $folder --all; done
        name: Publish npm Zen packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
