# This is a basic workflow to help you get started with Actions

name: release-jar

on:
  push:
    tags:
      - "*"
      
jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set tag env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'

      - uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: 1.10.1.693
          
      - name: Build jar
        run: make build
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/zen-fhir-${{ env.RELEASE_VERSION }}-standalone.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
