# This is a basic workflow to help you get started with Actions

name: release-jar

on:
  push:
    tags:
      - "*"
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set tag env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'

      - uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: 1.10.1.693
          
      - run: make build
        name: Build jar

      - name: Upload result of build
        uses: actions/upload-artifact@v2
        with:
          name: zen-fhir-latest.jar
          path: target/zen-fhir-standalone.jar
        
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download jar
        uses: actions/download-artifact@v2
        with:
          name: zen-fhir-latest.jar

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
