name: release

on:
  push:
    tags:
      - "*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.8.156

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Set tag env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '18'

      - uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: 1.10.1.693

      - run: bb init
        name: Install npm FHIR packages

      - name: Build jar
        run: bb build

      - run: bb init-r3
        name: Install npm R3 packages

      - name: Build standalone R3
        run: bb build-stanadlone-projects "r3/node_modules/" "zrc/standalone_projects/"

      - name: Build standalone projects
        run: bb build-standalone-zen-profiles-all-versions "node_modules/" "zrc/standalone_projects/"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/zen-fhir-${{ env.RELEASE_VERSION }}-standalone.jar, zrc/standalone_projects/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
