# This is a basic workflow to help you get started with Actions

name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '18'
      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.8.156
      - uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: 1.10.1.693
      - run: bb ci-test 0.1.0-test
