# This is a basic workflow to help you get started with Actions

name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v3.4.1
      - uses: actions/setup-java@v3.5.0
        with:
          distribution: "temurin"
          java-version: "18"
      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.5.0
        with:
          babashka-version: 0.8.156
      - uses: DeLaGuardo/setup-clojure@9.5
        with:
          cli: 1.11.1.1155
      - run: bb ci-test 0.1.0-test
